// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6d4g1NBLBK_RQ_1sSvSEkcgH7iqbUG4o',
    appId: '1:945947078385:web:e3e5b828c9b0ee3c49c350',
    messagingSenderId: '945947078385',
    projectId: 'auracity-ba9cb',
    authDomain: 'auracity-ba9cb.firebaseapp.com',
    storageBucket: 'auracity-ba9cb.firebasestorage.app',
    measurementId: 'G-DS4CYBEB8W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs4bAY_OQrLroCYcdbpv2yoXT9aKB5loc',
    appId: '1:945947078385:android:2f5fb8ef142637f449c350',
    messagingSenderId: '945947078385',
    projectId: 'auracity-ba9cb',
    storageBucket: 'auracity-ba9cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5_IdOF_S9Z9j6y73LLJu1Id2o9bzf530',
    appId: '1:945947078385:ios:a67c8f6f70cd56d849c350',
    messagingSenderId: '945947078385',
    projectId: 'auracity-ba9cb',
    storageBucket: 'auracity-ba9cb.firebasestorage.app',
    iosBundleId: 'com.auracity.auracity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5_IdOF_S9Z9j6y73LLJu1Id2o9bzf530',
    appId: '1:945947078385:ios:a67c8f6f70cd56d849c350',
    messagingSenderId: '945947078385',
    projectId: 'auracity-ba9cb',
    storageBucket: 'auracity-ba9cb.firebasestorage.app',
    iosBundleId: 'com.auracity.auracity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6d4g1NBLBK_RQ_1sSvSEkcgH7iqbUG4o',
    appId: '1:945947078385:web:1be787b9fad1378349c350',
    messagingSenderId: '945947078385',
    projectId: 'auracity-ba9cb',
    authDomain: 'auracity-ba9cb.firebaseapp.com',
    storageBucket: 'auracity-ba9cb.firebasestorage.app',
    measurementId: 'G-T5T6FEVWDW',
  );
}
